export const ROLES = ['END_USER', 'SUPPORT_TRIAGE', 'DEVELOPER', 'EXECUTIVE'];

export const ROLE_LABELS = {
  END_USER: 'End User',
  SUPPORT_TRIAGE: 'Support Triage',
  DEVELOPER: 'Developer',
  EXECUTIVE: 'Executive'
};

export const VIEWS_BY_ROLE = {
  END_USER: ['MY_INCIDENTS'],
  SUPPORT_TRIAGE: ['TRIAGE', 'INTEGRATIONS', 'PIPELINE'],
  DEVELOPER: ['DEVELOPER', 'INTEGRATIONS', 'PIPELINE'],
  EXECUTIVE: ['ADMIN', 'INTEGRATIONS', 'WARROOM', 'DIGITALTWIN', 'MISSIONCONTROL']
};

export const DEFAULT_VIEW_BY_ROLE = {
  END_USER: 'MY_INCIDENTS',
  SUPPORT_TRIAGE: 'TRIAGE',
  DEVELOPER: 'DEVELOPER',
  EXECUTIVE: 'ADMIN'
};


