export const CLOSED_STATUSES = ["RESOLVED", "CLOSED", "RESOLVED_DUPLICATE_MERGED", "SELF_SERVICE_RESOLVED", "VERIFIED", "KNOWLEDGE_CAPTURED"];
export const INCIDENT_STATUSES = [
  "NEW",
  "TRIAGING",
  "DIAGNOSED",
  "SELF_SERVICE_RESOLVED",
  "ASSIGNED",
  "IN_PROGRESS",
  "RESOLVED",
  "VERIFIED",
  "KNOWLEDGE_CAPTURED",
  "ESCALATED",
  "BLOCKED",
  "REOPENED"
];
export const ERP_MODULES = ["INVOICING", "PAYROLL", "INVENTORY", "GENERAL_LEDGER", "PROCUREMENT"];
export const ROLES = ["END_USER", "SUPPORT_TRIAGE", "DEVELOPER", "EXECUTIVE"];
export const STAFF_ROLES = ["SUPPORT_TRIAGE", "DEVELOPER", "EXECUTIVE"];
export const TRIAGE_ROLES = ["SUPPORT_TRIAGE"];
export const DEVELOPER_ROLES = ["DEVELOPER"];
export const EXECUTIVE_ROLES = ["EXECUTIVE"];
export const TRIAGE_AND_DEV_ROLES = ["SUPPORT_TRIAGE", "DEVELOPER"];
export const OPS_ROLES = ["SUPPORT_TRIAGE", "EXECUTIVE"];

