export const CLOSED_STATUSES = ["RESOLVED", "CLOSED", "RESOLVED_DUPLICATE_MERGED", "SELF_SERVICE_RESOLVED", "VERIFIED", "KNOWLEDGE_CAPTURED", "ROLLED_BACK"];
export const INCIDENT_STATUSES = [
  "NEW",
  "TRIAGED",
  "ASSIGNED",
  "IN_PROGRESS",
  "REMEDIATION_PENDING",
  "VERIFICATION",
  "VERIFICATION_FAILED",
  "ROLLBACK_REQUIRED",
  "ROLLED_BACK",
  "RESOLVED",
  "SELF_SERVICE_RESOLVED",
  "VERIFIED",
  "KNOWLEDGE_CAPTURED",
  "ESCALATED",
  "BLOCKED",
  "REOPENED"
];
export const ERP_MODULES = ["INVENTORY", "ORDERS", "PRODUCTION", "PROCUREMENT", "INVOICING", "PAYROLL", "GENERAL_LEDGER", "AUTH"];
export const ROLES = ["END_USER", "SUPPORT_TRIAGE", "DEVELOPER", "EXECUTIVE"];
export const STAFF_ROLES = ["SUPPORT_TRIAGE", "DEVELOPER", "EXECUTIVE"];
export const TRIAGE_ROLES = ["SUPPORT_TRIAGE"];
export const DEVELOPER_ROLES = ["DEVELOPER"];
export const EXECUTIVE_ROLES = ["EXECUTIVE"];
export const TRIAGE_AND_DEV_ROLES = ["SUPPORT_TRIAGE", "DEVELOPER"];
export const OPS_ROLES = ["SUPPORT_TRIAGE", "DEVELOPER", "EXECUTIVE"];


